server:
  port: 8080

spring:
  application:
    name: silver-job-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/oldboss}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: optional:file:./sql/schema.sql
      data-locations: optional:file:./sql/seed.sql

management:
  endpoints:
    web:
      exposure:
        include: health,info
